namespace Core;

public enum BindingID
{
    None = 0,

    // Movement
    MOVEFORWARD,
    MOVEBACKWARD,
    STRAFELEFT,
    STRAFERIGHT,
    JUMP,
    TURNLEFT,
    TURNRIGHT,
    TURNORACTION,
    MOVEANDSTEER,
    TOGGLEAUTORUN,
    TOGGLERUN,
    SITORSTAND,
    DISMOUNT,

    // Targeting
    TARGETSELF,
    TARGETNEAREST,
    TARGETNEARESTENEMY,
    TARGETNEARESTENEMYPLAYER,
    TARGETNEARESTFRIEND,
    TARGETNEARESTFRIENDPLAYER,
    TARGETPREVIOUS,
    TARGETPREVIOUSENEMY,
    TARGETPREVIOUSENEMYPLAYER,
    TARGETPREVIOUSFRIEND,
    TARGETPREVIOUSFRIENDPLAYER,
    TARGETMOUSEOVER,
    TARGETFOCUS,
    TARGETTALKER,
    TARGETLASTHOSTILE,
    TARGETLASTTARGET,
    ASSISTTARGET,
    TARGETPET,
    TARGETPARTYMEMBER1,
    TARGETPARTYMEMBER2,
    TARGETPARTYMEMBER3,
    TARGETPARTYMEMBER4,
    TARGETPARTYPET1,
    TARGETPARTYPET2,
    TARGETPARTYPET3,
    TARGETPARTYPET4,

    // Combat
    ATTACKTARGET,
    STARTATTACK,
    STOPATTACK,
    STOPCASTING,
    PETATTACK,

    // Interaction
    INTERACTTARGET,
    INTERACTMOUSEOVER,
    FOLLOWTARGET,

    // UI Toggles
    TOGGLEACTIONBARLOCK,
    TOGGLEAUTORUN2,
    TOGGLEBACKPACK,
    OPENALLBAGS,
    TOGGLECHARACTER0,
    TOGGLESPELLBOOK,
    TOGGLETALENTS,
    TOGGLEQUESTLOG,
    TOGGLEWORLDMAP,
    TOGGLEGAMEMENU,
    TOGGLEMINIMAP,
    TOGGLEMOUNTJOURNAL,
    TOGGLEPETJOURNAL,
    TOGGLEACHIEVEMENT,
    TOGGLEENCOUNTERJOURNAL,
    TOGGLECURRENCY,
    TOGGLESTATISTICS,

    // Action Bar - Main (slots 1-12)
    ACTIONBUTTON1,
    ACTIONBUTTON2,
    ACTIONBUTTON3,
    ACTIONBUTTON4,
    ACTIONBUTTON5,
    ACTIONBUTTON6,
    ACTIONBUTTON7,
    ACTIONBUTTON8,
    ACTIONBUTTON9,
    ACTIONBUTTON10,
    ACTIONBUTTON11,
    ACTIONBUTTON12,

    // Action Bar - Bottom Left (slots 61-72)
    MULTIACTIONBAR1BUTTON1,
    MULTIACTIONBAR1BUTTON2,
    MULTIACTIONBAR1BUTTON3,
    MULTIACTIONBAR1BUTTON4,
    MULTIACTIONBAR1BUTTON5,
    MULTIACTIONBAR1BUTTON6,
    MULTIACTIONBAR1BUTTON7,
    MULTIACTIONBAR1BUTTON8,
    MULTIACTIONBAR1BUTTON9,
    MULTIACTIONBAR1BUTTON10,
    MULTIACTIONBAR1BUTTON11,
    MULTIACTIONBAR1BUTTON12,

    // Action Bar - Bottom Right (slots 49-60)
    MULTIACTIONBAR2BUTTON1,
    MULTIACTIONBAR2BUTTON2,
    MULTIACTIONBAR2BUTTON3,
    MULTIACTIONBAR2BUTTON4,
    MULTIACTIONBAR2BUTTON5,
    MULTIACTIONBAR2BUTTON6,
    MULTIACTIONBAR2BUTTON7,
    MULTIACTIONBAR2BUTTON8,
    MULTIACTIONBAR2BUTTON9,
    MULTIACTIONBAR2BUTTON10,
    MULTIACTIONBAR2BUTTON11,
    MULTIACTIONBAR2BUTTON12,

    // Shapeshift
    SHAPESHIFTBUTTON1,
    SHAPESHIFTBUTTON2,
    SHAPESHIFTBUTTON3,
    SHAPESHIFTBUTTON4,
    SHAPESHIFTBUTTON5,
    SHAPESHIFTBUTTON6,
    SHAPESHIFTBUTTON7,
    SHAPESHIFTBUTTON8,
    SHAPESHIFTBUTTON9,
    SHAPESHIFTBUTTON10,

    // Camera
    CAMERAZOOMIN,
    CAMERAZOOMOUT,
    FLIPCAMERAYAW,

    // Chat
    OPENCHAT,
    OPENCHATSLASH,
    REPLY,

    // Raid Markers
    RAIDTARGET1,
    RAIDTARGET2,
    RAIDTARGET3,
    RAIDTARGET4,
    RAIDTARGET5,
    RAIDTARGET6,
    RAIDTARGET7,
    RAIDTARGET8,
    RAIDTARGETNONE,

    // Nameplates
    NAMEPLATES,
    FRIENDNAMEPLATES,

    // Miscellaneous
    SCREENSHOT,
    TOGGLESHEATH,
    TOGGLEFPS,
    TOGGLEUI,

    // Custom actions (secure buttons, not WoW built-ins)
    CUSTOM_STOPATTACK,
    CUSTOM_CLEARTARGET,
    CUSTOM_CONFIG,
    CUSTOM_FLUSH,
}
